# Generated by Django 5.2.4 on 2026-03-31 14:41

import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(storage=minio_storage.storage.MinioMediaStorage, upload_to='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
