# Generated by Django 5.2.4 on 2026-04-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.RemoveField(
            model_name='archive',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='archive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
