# Generated by Django 5.2.4 on 2025-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalaccessrule',
            name='access_rule',
        ),
        migrations.RemoveField(
            model_name='useraccessrule',
            name='access_rule',
        ),
        migrations.RemoveField(
            model_name='useraccessrule',
            name='user',
        ),
        migrations.AddField(
            model_name='portalaccessrule',
            name='access_rule_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccessrule',
            name='access_rule_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccessrule',
            name='user_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
