# Generated by Django 5.2.4 on 2025-07-17 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0002_remove_portalaccessrule_access_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='accessruletimezone',
            old_name='access_rule',
            new_name='access_rule_id',
        ),
        migrations.RenameField(
            model_name='accessruletimezone',
            old_name='time_zone',
            new_name='time_zone_id',
        ),
        migrations.AddField(
            model_name='template',
            name='finger_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='finger_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portalaccessrule',
            name='access_rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.accessrule'),
        ),
        migrations.AlterField(
            model_name='useraccessrule',
            name='access_rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.accessrule'),
        ),
        migrations.AlterField(
            model_name='useraccessrule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portalaccessrule',
            name='portal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.portal'),
        ),
    ]
