# Generated by Django 5.2.4 on 2025-07-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0004_alter_template_user_alter_template_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'managed': False},
        ),
    ]
