# Generated by Django 5.2.4 on 2025-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0006_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo do equipamento', max_length=255)),
                ('ip', models.CharField(help_text='IP ou hostname do equipamento. Ex: 192.168.0.129', max_length=255)),
                ('username', models.CharField(help_text='Usuário para autenticação', max_length=255)),
                ('password', models.CharField(help_text='Senha para autenticação', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Se o dispositivo está ativo para sincronização')),
                ('is_default', models.BooleanField(default=False, help_text='Se é o dispositivo padrão quando nenhum é especificado')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'control_id_device',
            },
        ),
    ]
