# Generated by Django 5.2.4 on 2025-07-18 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0007_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='device_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
