# Generated by Django 5.2.4 on 2025-07-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0009_alter_template_options_card_devices_alter_card_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='templates', to='control_id_django_app.device'),
        ),
    ]
