# Generated by Django 5.2.4 on 2025-07-18 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0010_template_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
