# Generated by Django 5.2.4 on 2025-07-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0011_alter_device_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
