# Generated by Django 5.2.4 on 2025-07-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0013_area_alter_accessrule_id_alter_portal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='area_from_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='portals_from', to='control_id_django_app.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portal',
            name='area_to_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='portals_to', to='control_id_django_app.area'),
            preserve_default=False,
        ),
    ]
