# Generated by Django 5.2.4 on 2025-08-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0015_customgroup_alter_timespan_end_alter_timespan_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.accessrule')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.customgroup')),
            ],
            options={
                'verbose_name': 'Grupo de Acesso',
                'verbose_name_plural': 'Grupos de Acesso',
                'db_table': 'group_access_rules',
                'unique_together': {('group', 'access_rule')},
            },
        ),
    ]
