# Generated by Django 5.2.4 on 2025-08-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0016_groupaccessrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(1, 'Equipamento Invalido'), (2, 'Parametro De Identificacao Invalido'), (3, 'Não Identificado'), (4, 'Identificacao Pendente'), (5, 'Tempo De Identificacao Esgotado'), (6, 'Acesso Negado'), (7, 'Acesso Concedido'), (8, 'Acesso Pendente'), (9, 'Usuario Nao E Adm'), (10, 'Acesso Nao Identificado'), (11, 'Acesso Por Botoeira'), (12, 'Acesso Pela Interface Web'), (13, 'Desistencia De Entrada'), (14, 'Sem Resposta'), (15, 'Acesso Pela Interfonia')])),
                ('identifier_id', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255)),
                ('uhf_value', models.CharField(max_length=255)),
                ('pin_value', models.CharField(max_length=255)),
                ('card_value', models.CharField(max_length=255)),
                ('confidence', models.IntegerField()),
                ('mask', models.CharField(max_length=255)),
                ('access_rule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control_id_django_app.accessrule')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control_id_django_app.device')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control_id_django_app.portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'db_table': 'access_logs',
                'ordering': ['-time'],
            },
        ),
    ]
