# Generated by Django 5.2.4 on 2025-08-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0017_accesslogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
