# Generated by Django 5.2.4 on 2025-08-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0018_alter_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessruletimezone',
            old_name='access_rule_id',
            new_name='access_rule',
        ),
        migrations.RenameField(
            model_name='accessruletimezone',
            old_name='time_zone_id',
            new_name='time_zone',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='area_from_id',
            new_name='area_from',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='area_to_id',
            new_name='area_to',
        ),
        migrations.RenameField(
            model_name='portalaccessrule',
            old_name='access_rule_id',
            new_name='access_rule',
        ),
        migrations.RenameField(
            model_name='portalaccessrule',
            old_name='portal_id',
            new_name='portal',
        ),
        migrations.RenameField(
            model_name='useraccessrule',
            old_name='access_rule_id',
            new_name='access_rule',
        ),
        migrations.RenameField(
            model_name='useraccessrule',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
