# Generated by Django 5.2.4 on 2025-09-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0018_alter_accesslogs_user'),
        ('control_id_django_app', '0019_rename_access_rule_id_accessruletimezone_access_rule_and_more'),
    ]

    operations = [
    ]
