# Generated by Django 5.2.4 on 2025-09-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0020_merge_20250912_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessruletimezone',
            options={'verbose_name': 'Regra de Acesso - Zona de Tempo', 'verbose_name_plural': 'Regras de Acesso - Zonas de Tempo'},
        ),
        migrations.AlterField(
            model_name='accesslogs',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accessruletimezone',
            unique_together={('access_rule', 'time_zone')},
        ),
    ]
