# Generated by Django 5.2.4 on 2025-09-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0022_alter_accesslogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogs',
            name='access_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_id_django_app.accessrule'),
        ),
        migrations.AlterField(
            model_name='accesslogs',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_id_django_app.portal'),
        ),
    ]
