# Generated by Django 5.2.4 on 2025-09-29 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('control_id_django_app', '0023_alter_accesslogs_access_rule_alter_accesslogs_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['time'], name='access_logs_time_252b52_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['event_type'], name='access_logs_event_t_75ec89_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['device'], name='access_logs_device__0bd07a_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['user'], name='access_logs_user_id_4502b2_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['portal'], name='access_logs_portal__ba90be_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['access_rule'], name='access_logs_access__3fc083_idx'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group'),
        ),
    ]
