# Generated by Django 5.2.1 on 2025-09-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0024_accesslogs_access_logs_time_252b52_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_id_django_app.customgroup'),
        ),
    ]
