# Generated by Django 5.2.4 on 2026-02-19 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0025_alter_usergroup_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslogs',
            index=models.Index(fields=['device', 'identifier_id', 'time'], name='access_logs_device__cbcf0b_idx'),
        ),
    ]
