# Generated by Django 5.2.1 on 2026-03-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0028_temporaryuserrelease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('requested_by_role', models.CharField(blank=True, default='', max_length=50)),
                ('requested_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('target_user_name', models.CharField(blank=True, default='', max_length=255)),
                ('target_user_registration', models.CharField(blank=True, default='', max_length=50)),
                ('release_type', models.CharField(choices=[('device_event', 'Liberação por evento'), ('single_turn', 'Giro único'), ('scheduled_user_release', 'Liberação agendada'), ('temporary_user_release', 'Liberação temporária')], max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('sent', 'Enviada'), ('active', 'Ativa'), ('consumed', 'Consumida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits', to='control_id_django_app.accesslogs')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits', to='control_id_django_app.device')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits', to='control_id_django_app.portal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits_requested', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits_targeted', to=settings.AUTH_USER_MODEL)),
                ('temporary_release', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audit', to='control_id_django_app.temporaryuserrelease')),
            ],
            options={
                'verbose_name': 'Auditoria de Liberação',
                'verbose_name_plural': 'Auditorias de Liberação',
                'db_table': 'release_audits',
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['release_type', 'status'], name='release_aud_release_f3fe5a_idx'), models.Index(fields=['requested_by', 'requested_at'], name='release_aud_request_e256dd_idx'), models.Index(fields=['target_user', 'requested_at'], name='release_aud_target__3a9561_idx'), models.Index(fields=['device', 'requested_at'], name='release_aud_device__a3dfc5_idx'), models.Index(fields=['scheduled_for'], name='release_aud_schedul_e6cb73_idx')],
            },
        ),
    ]
