# Generated by Django 5.2.4 on 2026-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0030_accesslogs_raw_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogs',
            name='sentido',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
