# Generated by Django 5.2.4 on 2026-03-30 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0031_accesslogs_sentido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryGroupRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('consumed', 'Consumida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('result_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_group_releases', to='control_id_django_app.accessrule')),
                ('consumed_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_temporary_group_releases', to='control_id_django_app.accesslogs')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_group_releases', to='control_id_django_app.customgroup')),
                ('group_access_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_group_releases', to='control_id_django_app.groupaccessrule')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_temporary_group_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liberação Temporária',
                'verbose_name_plural': 'Liberações Temporárias',
                'db_table': 'temporary_group_releases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='temporary_g_status_db2d13_idx'), models.Index(fields=['group', 'status'], name='temporary_g_group_i_ae42af_idx'), models.Index(fields=['valid_from', 'status'], name='temporary_g_valid_f_246f66_idx'), models.Index(fields=['valid_until', 'status'], name='temporary_g_valid_u_176799_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('group',), name='unique_open_temporary_release_per_group')],
            },
        ),
    ]
