# Generated by Django 5.2.4 on 2026-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0035_biometriccapturesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometriccapturesession',
            name='deleted',
        ),
        migrations.AddField(
            model_name='biometriccapturesession',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
