# Generated by Django 5.2.4 on 2026-04-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0036_remove_biometriccapturesession_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='portal_groups', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Grupo de Portais',
                'verbose_name_plural': 'Grupos de Portais',
                'db_table': 'portal_groups',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='temporarygrouprelease',
            name='portal_group',
            field=models.ForeignKey(blank=True, help_text='Se definido, a liberacao se aplica apenas as catracas deste grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_group_releases', to='control_id_django_app.portalgroup'),
        ),
        migrations.AddField(
            model_name='temporaryuserrelease',
            name='portal_group',
            field=models.ForeignKey(blank=True, help_text='Se definido, a liberação se aplica apenas às catracas deste grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_user_releases', to='control_id_django_app.portalgroup'),
        ),
        migrations.CreateModel(
            name='PortalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_devices', to='control_id_django_app.device')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_devices', to='control_id_django_app.portal')),
                ('portal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_devices', to='control_id_django_app.portalgroup')),
            ],
            options={
                'verbose_name': 'Portal-Dispositivo',
                'verbose_name_plural': 'Portal-Dispositivos',
                'db_table': 'portal_device_mappings',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('portal', 'device'), name='unique_portal_device')],
            },
        ),
    ]
