# Generated by Django 5.2.4 on 2026-04-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_django_app', '0037_portalgroup_temporarygrouprelease_portal_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupaccessrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupaccessrule',
            name='portal_group',
            field=models.ForeignKey(blank=True, help_text='Se definido, a regra se aplica apenas as catracas deste grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_access_rules', to='control_id_django_app.portalgroup'),
        ),
        migrations.AddField(
            model_name='useraccessrule',
            name='portal_group',
            field=models.ForeignKey(blank=True, help_text='Se definido, a regra se aplica apenas as catracas deste grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_access_rules', to='control_id_django_app.portalgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupaccessrule',
            unique_together={('group', 'access_rule', 'portal_group')},
        ),
    ]
