# Generated by Peraza 5.2.4 on 2026-04-16 10:21

from django.db import migrations


GROUPS = [
    {"id": 1, "name": "Padrão"},
    {"id": 2, "name": "Visitas"},
]

AREAS = [
    {"id": 1, "name": "Saída"},
    {"id": 2, "name": "Entrada"},
]

PORTALS = [
    {"id": 1, "name": "Portal de Entrada", "area_from_id": 1, "area_to_id": 2},
    {"id": 2, "name": "Portal de Saída", "area_from_id": 2, "area_to_id": 1},
]

ACCESS_RULES = [
    {"id": 1, "name": "Regra de acesso padrão para o Grupo 1", "type": 1, "priority": 0},
    {"id": 2, "name": "Regra de acesso padrão para o Grupo 2", "type": 1, "priority": 0},
    {"id": 3, "name": "(Regra de Acesso automaticamente criada para o Grupo 1)", "type": 1, "priority": 0},
]

PORTAL_ACCESS_RULES = [
    {"portal_id": 1, "access_rule_id": 3},
    {"portal_id": 2, "access_rule_id": 3},
]

GROUP_ACCESS_RULES = [
    {"group_id": 2, "access_rule_id": 2},
    {"group_id": 1, "access_rule_id": 3},
]

TIME_ZONES = [
    {"id": 1, "name": "Sempre Liberado"},
]

TIME_SPANS = [
    {
        "id": 1,
        "time_zone_id": 1,
        "start": 0,
        "end": 86399,
        "sun": True,
        "mon": True,
        "tue": True,
        "wed": True,
        "thu": True,
        "fri": True,
        "sat": True,
        "hol1": True,
        "hol2": True,
        "hol3": True,
    }
]

ACCESS_RULE_TIME_ZONES = [
    {"access_rule_id": 1, "time_zone_id": 1},
    {"access_rule_id": 3, "time_zone_id": 1},
]


def populate(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Area = apps.get_model("control_id_django_app", "Area")
    Portal = apps.get_model("control_id_django_app", "Portal")
    AccessRule = apps.get_model("control_id_django_app", "AccessRule")
    PortalAccessRule = apps.get_model("control_id_django_app", "PortalAccessRule")
    GroupAccessRule = apps.get_model("control_id_django_app", "GroupAccessRule")
    TimeZone = apps.get_model("control_id_django_app", "TimeZone")
    TimeSpan = apps.get_model("control_id_django_app", "TimeSpan")
    AccessRuleTimeZone = apps.get_model("control_id_django_app", "AccessRuleTimeZone")

    if any(
        (
            Group.objects.exists(),
            Area.objects.exists(),
            Portal.objects.exists(),
            AccessRule.objects.exists(),
            PortalAccessRule.objects.exists(),
            GroupAccessRule.objects.exists(),
            TimeZone.objects.exists(),
            TimeSpan.objects.exists(),
            AccessRuleTimeZone.objects.exists(),
        )
    ):
        return

    for group_data in GROUPS:
        Group.objects.create(
            id=group_data["id"],
            name=group_data["name"],
        )

    for area_data in AREAS:
        Area.objects.create(
            id=area_data["id"],
            name=area_data["name"],
        )

    for portal_data in PORTALS:
        Portal.objects.create(
            id=portal_data["id"],
            name=portal_data["name"],
            area_from_id=portal_data["area_from_id"],
            area_to_id=portal_data["area_to_id"],
        )

    for access_rule_data in ACCESS_RULES:
        AccessRule.objects.create(
            id=access_rule_data["id"],
            name=access_rule_data["name"],
            type=access_rule_data["type"],
            priority=access_rule_data["priority"],
        )

    for time_zone_data in TIME_ZONES:
        TimeZone.objects.create(
            id=time_zone_data["id"],
            name=time_zone_data["name"],
        )

    for time_span_data in TIME_SPANS:
        TimeSpan.objects.create(
            id=time_span_data["id"],
            time_zone_id=time_span_data["time_zone_id"],
            start=time_span_data["start"],
            end=time_span_data["end"],
            sun=time_span_data["sun"],
            mon=time_span_data["mon"],
            tue=time_span_data["tue"],
            wed=time_span_data["wed"],
            thu=time_span_data["thu"],
            fri=time_span_data["fri"],
            sat=time_span_data["sat"],
            hol1=time_span_data["hol1"],
            hol2=time_span_data["hol2"],
            hol3=time_span_data["hol3"],
        )

    for relation in PORTAL_ACCESS_RULES:
        PortalAccessRule.objects.create(
            portal_id=relation["portal_id"],
            access_rule_id=relation["access_rule_id"],
        )

    for relation in GROUP_ACCESS_RULES:
        GroupAccessRule.objects.create(
            group_id=relation["group_id"],
            access_rule_id=relation["access_rule_id"],
            portal_group_id=None,
        )

    for relation in ACCESS_RULE_TIME_ZONES:
        AccessRuleTimeZone.objects.create(
            access_rule_id=relation["access_rule_id"],
            time_zone_id=relation["time_zone_id"],
        )

    # O payload original da catraca tambem cita "area_access_rules", mas o
    # schema Django atual nao possui uma model/tabela correspondente para esse
    # relacionamento. Por isso esse trecho nao e populado aqui.


class Migration(migrations.Migration):
    dependencies = [
        (
            "control_id_django_app",
            "0038_alter_groupaccessrule_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate, migrations.RunPython.noop),
    ]
