# Generated by Django 5.2.4 on 2025-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type_id',
            field=models.IntegerField(blank=True, help_text='Visitantes terão id 1, usuarios cadastrados serão nulo', null=True),
        ),
    ]
