# Generated by Django 5.2.4 on 2025-07-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0003_user_user_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Visitor')], help_text='Visitantes terão id 1, usuarios cadastrados serão nulo', null=True),
        ),
    ]
