# Generated by Django 5.2.4 on 2025-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0004_alter_user_user_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
