# Generated by Django 5.2.4 on 2026-02-19 10:29

import src.core.user.infra.user_django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0005_alter_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=src.core.user.infra.user_django_app.models.generate_pin, help_text="PIN de 4 dígitos para acesso na catraca (campo 'password' na API Control iD)", max_length=4),
        ),
    ]
