# Generated by Django 5.2.1 on 2026-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0006_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_role',
            field=models.CharField(blank=True, choices=[('', 'Sem perfil'), ('admin', 'Administrador'), ('guarita', 'Guarita'), ('sisae', 'SISAE')], default='', help_text='Perfil de aplicação para acesso ao painel.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='panel_access_only',
            field=models.BooleanField(default=False, help_text='Quando ativo, a conta é apenas do painel e não deve ser sincronizada com as catracas.'),
        ),
    ]
