# Generated by Django 5.2.4 on 2026-03-25

from django.db import migrations


def set_unusable_password_for_nulls(apps, schema_editor):
    User = apps.get_model("user_django_app", "User")
    User.objects.filter(password__isnull=True).update(password="!")


class Migration(migrations.Migration):
    dependencies = [
        ("user_django_app", "0007_user_app_role_user_panel_access_only"),
    ]

    operations = [
        migrations.RunPython(set_unusable_password_for_nulls, migrations.RunPython.noop),
    ]

