# Generated by Django 5.2.4 on 2026-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0008_fix_null_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
