# Generated by Django 5.2.4 on 2026-04-02 14:44

import src.core.user.infra.user_django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0012_user_device_scope_and_selected_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_role',
            field=models.CharField(blank=True, choices=[('', 'Sem perfil'), ('admin', 'Administrador'), ('guarita', 'Guarita'), ('sisae', 'SISAE')], default='', help_text='Perfil de aplicacao para acesso ao painel.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='panel_access_only',
            field=models.BooleanField(default=False, help_text='Quando ativo, a conta e apenas do painel e nao deve ser sincronizada com as catracas.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(default=src.core.user.infra.user_django_app.models.generate_pin, help_text='PIN de 4 digitos para acesso na catraca (campo password na API Control iD).', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'Visitor')], help_text='Visitantes terao id 1, usuarios cadastrados serao nulo', null=True),
        ),
    ]
