# Generated by Django 5.2.4 on 2026-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0015_user_start_date_user_end_date_user_last_passage_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_role',
            field=models.CharField(blank=True, choices=[('', 'Sem perfil'), ('admin', 'Administrador'), ('guarita', 'Guarita'), ('sisae', 'SISAE'), ('aluno', 'Aluno'), ('servidor', 'Servidor')], default='aluno', help_text='Perfil de aplicacao para acesso ao painel.', max_length=20),
        ),
    ]
