# Generated by Django 5.2.4 on 2025-09-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_id_django_app', '0023_alter_accesslogs_access_rule_alter_accesslogs_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beep_enabled', models.BooleanField(default=True, help_text='Habilitar som de beep')),
                ('bell_enabled', models.BooleanField(default=False, help_text='Habilitar campainha')),
                ('bell_relay', models.IntegerField(default=1, help_text='Relé da campainha')),
                ('ssh_enabled', models.BooleanField(default=False, help_text='Habilitar SSH')),
                ('relayN_enabled', models.BooleanField(default=False, help_text='Habilitar relé N')),
                ('relayN_timeout', models.IntegerField(default=5, help_text='Timeout do relé N em segundos')),
                ('relayN_auto_close', models.BooleanField(default=True, help_text='Fechar relé automaticamente')),
                ('door_sensorN_enabled', models.BooleanField(default=False, help_text='Habilitar sensor de porta N')),
                ('door_sensorN_idle', models.IntegerField(default=10, help_text='Tempo de inatividade do sensor em segundos')),
                ('doorN_interlock', models.BooleanField(default=False, help_text='Intertravamento da porta N')),
                ('exception_mode', models.BooleanField(default=False, help_text='Modo de exceção')),
                ('doorN_exception_mode', models.BooleanField(default=False, help_text='Modo de exceção da porta N')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração de Hardware',
                'verbose_name_plural': 'Configurações de Hardware',
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_only', models.BooleanField(default=False, help_text='Aceitar apenas senha')),
                ('hide_password_only', models.BooleanField(default=False, help_text='Ocultar entrada de senha')),
                ('password_only_tip', models.CharField(blank=True, help_text='Dica para senha', max_length=255)),
                ('hide_name_on_identification', models.BooleanField(default=False, help_text='Ocultar nome na identificação')),
                ('denied_transaction_code', models.CharField(blank=True, help_text='Código para transação negada', max_length=10)),
                ('send_code_when_not_identified', models.BooleanField(default=False, help_text='Enviar código quando não identificado')),
                ('send_code_when_not_authorized', models.BooleanField(default=False, help_text='Enviar código quando não autorizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração de Segurança',
                'verbose_name_plural': 'Configurações de Segurança',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reboot_hour', models.IntegerField(default=3, help_text='Hora para reinicialização automática')),
                ('auto_reboot_minute', models.IntegerField(default=0, help_text='Minuto para reinicialização automática')),
                ('clear_expired_users', models.BooleanField(default=False, help_text='Limpar usuários expirados')),
                ('keep_user_image', models.BooleanField(default=True, help_text='Manter imagens dos usuários')),
                ('url_reboot_enabled', models.BooleanField(default=True, help_text='Habilitar reinicialização via URL')),
                ('web_server_enabled', models.BooleanField(default=True, help_text='Habilitar servidor web')),
                ('online', models.BooleanField(default=True, help_text='Modo online')),
                ('local_identification', models.BooleanField(default=True, help_text='Identificação local')),
                ('language', models.CharField(default='pt', help_text='Idioma do sistema', max_length=10)),
                ('daylight_savings_time_start', models.DateTimeField(blank=True, help_text='Início do horário de verão', null=True)),
                ('daylight_savings_time_end', models.DateTimeField(blank=True, help_text='Fim do horário de verão', null=True)),
                ('catra_timeout', models.IntegerField(default=30, help_text='Timeout da catraca em segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='UIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_always_on', models.BooleanField(default=False, help_text='Tela sempre ligada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração de Interface',
                'verbose_name_plural': 'Configurações de Interface',
            },
        ),
    ]
