# Generated by Django 5.2.4 on 2025-09-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0001_initial'),
        ('control_id_django_app', '0025_alter_usergroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração de Monitor',
                'verbose_name_plural': 'Configurações de Monitor',
            },
        ),
    ]
