# Generated by Django 5.2.4 on 2025-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0002_monitorconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorconfig',
            name='data',
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='alive_interval',
            field=models.IntegerField(default=30000, help_text='Intervalo ms para device_is_alive no standalone'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='hostname',
            field=models.CharField(blank=True, default='', help_text='Hostname/IP do servidor de monitor', max_length=255),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='inform_access_event_id',
            field=models.IntegerField(default=0, help_text='Reportar id de access_events nos endpoints'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='path',
            field=models.CharField(blank=True, default='api/notifications', help_text='Endpoint de notificações do monitor', max_length=255),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='port',
            field=models.CharField(blank=True, default='', help_text='Porta do servidor de monitor', max_length=10),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='request_timeout',
            field=models.IntegerField(default=1000, help_text='Tempo em ms para timeout da request'),
        ),
    ]
