# Generated by Django 5.2.4 on 2025-10-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0003_remove_monitorconfig_data_and_more'),
        ('control_id_django_app', '0025_alter_usergroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorconfig',
            name='alive_interval',
        ),
        migrations.RemoveField(
            model_name='monitorconfig',
            name='inform_access_event_id',
        ),
        migrations.CreateModel(
            name='CatraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_passback', models.BooleanField(default=False, help_text='Habilita ou desabilita o controle de anti-dupla entrada')),
                ('daily_reset', models.BooleanField(default=False, help_text='Habilita o reset de logs para o controle de anti-dupla entrada (meia-noite)')),
                ('gateway', models.CharField(choices=[('clockwise', 'Horário'), ('anticlockwise', 'Anti-horário')], default='clockwise', help_text='Sentido da entrada (horário ou anti-horário)', max_length=20)),
                ('operation_mode', models.CharField(choices=[('blocked', 'Ambas controladas'), ('entrance_open', 'Entrada liberada'), ('exit_open', 'Saída liberada'), ('both_open', 'Ambas liberadas')], default='blocked', help_text='Modo de operação da catraca', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catra_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração da Catraca',
                'verbose_name_plural': 'Configurações da Catraca',
            },
        ),
        migrations.CreateModel(
            name='PushServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_request_timeout', models.IntegerField(default=15000, help_text='Timeout das requisições do equipamento para o servidor em milissegundos')),
                ('push_request_period', models.IntegerField(default=60, help_text='Período entre as requisições de push em segundos')),
                ('push_remote_address', models.CharField(blank=True, default='', help_text='Endereço IP e porta em que o servidor está rodando (ex: 192.168.120.94:80)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_server_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração do Servidor Push',
                'verbose_name_plural': 'Configurações do Servidor Push',
            },
        ),
    ]
