# Generated by Django 5.2.4 on 2026-02-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0004_remove_monitorconfig_alive_interval_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorConfig',
        ),
    ]
