# Generated by Django 5.2.1 on 2026-03-06 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0005_delete_monitorconfig'),
        ('control_id_django_app', '0026_accesslogs_access_logs_device__cbcf0b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasySetupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('success', 'Sucesso'), ('partial', 'Parcial (com avisos)'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easy_setup_logs', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Easy Setup Log',
                'verbose_name_plural': 'Easy Setup Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
