# Generated by Django 5.2.4 on 2026-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_id_config_django_app', '0009_hardware_network_interlock_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catraconfig',
            name='gateway',
            field=models.CharField(choices=[('clockwise', 'Horário'), ('anticlockwise', 'Anti-horário')], default='anticlockwise', help_text='Sentido da entrada (horário ou anti-horário)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hardwareconfig',
            name='relayN_auto_close',
            field=models.BooleanField(default=False, help_text='Fechar rel? automaticamente'),
        ),
        migrations.AlterField(
            model_name='hardwareconfig',
            name='ssh_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar SSH'),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='password_only_tip',
            field=models.CharField(help_text='Dica para senha', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='catra_timeout',
            field=models.IntegerField(default=5000, help_text='Timeout da catraca em milissegundos'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='online',
            field=models.BooleanField(default=False, help_text='Modo online'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='url_reboot_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar reinicialização via URL'),
        ),
        migrations.AlterField(
            model_name='uiconfig',
            name='screen_always_on',
            field=models.BooleanField(default=True, help_text='Tela sempre ligada'),
        ),
    ]
