# Generated by Django 5.2.4 on 2025-10-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_id_django_app', '0025_alter_usergroup_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timeout', models.IntegerField(default=1000, help_text='Tempo em ms para timeout da request HTTP que a catraca envia')),
                ('hostname', models.CharField(blank=True, default='', help_text='Hostname ou IP do servidor que vai receber notificações (ex: api.exemplo.com ou 192.168.1.100)', max_length=255)),
                ('port', models.CharField(blank=True, default='', help_text='Porta do servidor de monitor (ex: 80, 443, 8000)', max_length=10)),
                ('path', models.CharField(blank=True, default='api/notifications', help_text='Endpoint/path do servidor onde a catraca vai enviar (ex: /api/monitor/events)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(help_text='Dispositivo/catraca vinculada a esta configuração de monitor', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_config', to='control_id_django_app.device')),
            ],
            options={
                'verbose_name': 'Configuração de Monitor',
                'verbose_name_plural': 'Configurações de Monitor',
                'db_table': 'control_id_monitor_config',
            },
        ),
    ]
